# Tutorial 
# Created by SKR and used as template for Walk Through 4 lecture of JeremyH
## Modified from the pets dataset notebook ## 



Setup the notebook for my own environment

In [ ]:
# do something like this - copy over from fastai2 walkthru 
# !nvidia-smi -L

In [ ]:
# make your Google drive accessible 
from google.colab import drive
drive.mount('/content/gdrive', force_remount=True)
root_dir = "/content/gdrive/My Drive/"
base_dir = root_dir + 'fastai2_library/course-v4/'

# navigate to the notebooks directory for dl2
import os
os.chdir(base_dir)

Mounted at /content/gdrive


In [ ]:
!pwd
# cd to base_dir if above os.chdir does not work using below command
# %cd "/content/gdrive/My Drive/fastai/course-v4/"

/content/gdrive/My Drive/fastai2_library/course-v4


In [ ]:
!pip install -q -r requirements.txt

In [ ]:
%cd nbs

/content/gdrive/My Drive/fastai2_library/course-v4/nbs


### Jeremy Setup at beginning of notebook

In [ ]:
# original imports in JH notebook
#from local.torch_basics import *
#from local.test import *
#from local.data.all import *
#from local.vision.core import *
#from local.notebook.showdoc import *

# imports in mnist nb
from fastai2.vision.all import *
from utils import *

First we'll have a look at the basic steps using a single MNIST image. We'll start with a filename, and see step by step how it can be converted in to a labelled image that can be displayed and used for modeling. We use the usual `untar_data` to download our dataset (if necessary) and get all the image files:

In [ ]:
source = untar_data(URLs.MNIST_TINY)/'train'
items = get_image_files(source)
fn = items[0]; fn

Path('/root/.fastai/data/mnist_tiny/train/3/7214.png')

In [ ]:
def neg(x): return -x

In [ ]:
neg(3)

-3

In [ ]:
tup = (1, 3)

In [ ]:
neg(tup)

TypeError: ignored

Above does NOT work is a design choice in Python. 

In [ ]:
arr = array([1, 3])

In [ ]:
neg(arr)

array([-1, -3])

Neg works - so different behavior.

Python lets us change its behavior depending on domain. In DS domain, we are interested in tuple like things coz generally 
we have X and Y. 
eg Image (X) and Label (Y), in classification;
source image(X), mask (Y) in segmentation;
(image tuple) (X), bool(Y) for Siamese;
(conts, cats) (X), targ(Y) for Tabular.

We would like Python to have neg behave more like it does for arrays 

ONE WAY to change behavior of a Python function is to use a DECORATOR 

In [ ]:
@Transform
def neg(x): return -x

In [ ]:
# this works
neg(tup)

(-1, -3)

In [ ]:
# Let us grab an image
img = load_image(fn); img

In [ ]:
# Create a  tensor of the image
timg = tensor(array(img)).float() # need the float here or else unsigned int so neg does not work. 
# Let us look at few rows of it
tsub = timg[12:15]
tsub

tensor([[  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   3.,  34., 210., 254., 253., 179.,  64.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
        [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0., 105., 253., 253., 254., 114.,  11.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
        [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,  22., 210., 253., 253., 121.,   6.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.]])

In [ ]:
neg(tsub)

tensor([[  -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -3.,  -34., -210., -254., -253., -179.,  -64.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.,
           -0.],
        [  -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0., -105., -253., -253., -254., -114.,  -11.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.,
           -0.],
        [  -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.,  -22., -210., -253., -253., -121.,   -6.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.,
           -0.]])

In [ ]:
neg((tsub, tsub))

(tensor([[  -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -3.,  -34., -210., -254., -253., -179.,  -64.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.,
            -0.],
         [  -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0., -105., -253., -253., -254., -114.,  -11.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.,
            -0.],
         [  -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.,  -22., -210., -253., -253., -121.,   -6.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.,
            -0.]]),
 tensor([[  -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -3.,  -34., -210., -254., -253., -179.,  -64.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.,
            -0.],
         [  -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0., -105., -253., -253., -254., -114.,  -11.,  

Let us try a more interesting function: A Normalization function which would be useful to have in a transformation pipeline. 

In [ ]:
# At first just a function to normalize
def norm(x, m, s): return (x-m)/s

In [ ]:
nimg = norm(timg, 127., 50.)
nimg[12:15]

tensor([[-2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.4800, -1.8600,  1.6600,  2.5400,  2.5200,  1.0400, -1.2600, -2.5400, -2.5400, -2.5400,
         -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400],
        [-2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -0.4400,  2.5200,  2.5200,  2.5400, -0.2600, -2.3200, -2.5400, -2.5400, -2.5400, -2.5400,
         -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400],
        [-2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.1000,  1.6600,  2.5200,  2.5200, -0.1200, -2.4200, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
         -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400]])

In [ ]:
timg.mean(), nimg.mean()

(tensor(28.2219), tensor(-1.9756))

Typically though we would like to run this function on GPU as it can execute much faster on GPU. BUT by the time this data (here an image) ends up on GPU it will NOT just be an image. It will be an image AND a label. 

In [ ]:
# So let us create an tuple which is an image and an int value
imgtup = (timg, 1)

In [ ]:
# Something like what we will actually be working with on the GPU
imgtup

(tensor([[  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
         [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
         [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
         [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
         [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
         [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,  26., 213., 169., 121., 121., 192., 121.,

In [ ]:
# If we wish to normalize that - AGAIN PROBLEM 
# So need a transform
norm(imgtup, m=127., s=50.)

TypeError: ignored

In [ ]:
@Transform
def norm(x, m, s): return (x-m)/s

In [ ]:
nimg = norm(timg, m=127., s=50.)
nimg[12:15]

tensor([[-2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.4800, -1.8600,  1.6600,  2.5400,  2.5200,  1.0400, -1.2600, -2.5400, -2.5400, -2.5400,
         -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400],
        [-2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -0.4400,  2.5200,  2.5200,  2.5400, -0.2600, -2.3200, -2.5400, -2.5400, -2.5400, -2.5400,
         -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400],
        [-2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.1000,  1.6600,  2.5200,  2.5200, -0.1200, -2.4200, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
         -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400]])

In [ ]:
timg.mean(), nimg.mean()

(tensor(28.2219), tensor(-1.9756))

In [ ]:
imgtup = (timg, 1)

In [ ]:
norm(imgtup, m=127., s=50.)
# Working again BUT a problem if you look at below this function ALSO 
# Transformed our label - NOT what we want.

(tensor([[-2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
          -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400],
         [-2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
          -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400],
         [-2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
          -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400],
         [-2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, 

We want a WAY to apply the Norm Transform to ONLY THOSE ITEMS that we wish to NORMALIZE. We can add a Type notation to say what to apply it to. The issue is that by the time you get to the dataloader(s) everything is a Tensor so how do you decide which bits of the Tuple to apply the Transform to. 

The Answer: We create things that INHERIT from a Tensor. Fastai has TensorBase which is the base class for things that inherit from Tensor. So then we do the following.

In [ ]:
TensorBase??

In [ ]:
# This cell created to inherit from Tensor
class MyTensorImg(TensorBase): pass 

In [ ]:
# mti is exactly like a Tensor and does tensory thing - add, sub etc
mti = MyTensorImg(timg)

In [ ]:
# Check its type
type(mti)

__main__.MyTensorImg

Now we can start constraining our function (a Transform) to work ONLY on things we want. So a Transform can be made to work only on a particular type. So if you are applying to a Tuple, it will only apply to this type. 

In [ ]:
@Transform
def norm(x:MyTensorImg, m, s): return (x-m)/s

In [ ]:
imgtup = (mti, 1)

In [ ]:
# Look at that label now - it has NOT been transformed.
# So Transform is applied only to type MyTensorImg
norm(imgtup, m=127., s=50.)

(MyTensorImg([[-2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
          -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400],
         [-2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
          -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400],
         [-2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
          -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400],
         [-2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5

This behavior is NO MORE STRANGE than typical python dispatch. Different languages, libraries have different dispatch methods. Julia dispatches similar to this way of dispatching based on types described here but Python BY DEFAULT does it differently and we are just picking A WAY to do this. So this is just another way of doing FUNCTION DISPATCH in Python.

Do Transforms only apply to Tensors? Note: The second part of imgtup is an int 1 and we saw the Norm transform apply to 1 so we got -2.52.

In [ ]:
class MyInt(int): pass

In [ ]:
mi = MyInt(1)

In [ ]:
@Transform
def norm(x:MyInt, m, s): return (x-m)/s

In [ ]:
imgtup = (mti, mi)

In [ ]:
# Now the img tensor does NOT get transformed ONLY the label does
norm(imgtup, m=127., s=50.)

(MyTensorImg([[  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
         [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
         [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
         [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
         [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
         [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,  26., 213., 169., 121., 121., 192., 

In [ ]:
@Transform
def norm(x:Tensor, m, s): return (x-m)/s

One issue is that we do NOT want to pass the mean and sd every time, so 

In [ ]:
m,s = timg.mean(), timg.std()

In [ ]:
f = partial(norm, m=m, s=s)

In [ ]:
nimg = f(timg)
nimg[12:15]

tensor([[-0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3475,  0.0796,  2.5045,  3.1107,  3.0969,  2.0774,  0.4929, -0.3888, -0.3888, -0.3888,
         -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888],
        [-0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888,  1.0578,  3.0969,  3.0969,  3.1107,  1.1818, -0.2373, -0.3888, -0.3888, -0.3888, -0.3888,
         -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888],
        [-0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.0857,  2.5045,  3.0969,  3.0969,  1.2783, -0.3062, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888,
         -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888]])

In [ ]:
imgtup = (timg, mi)

In [ ]:
# This is how we would like Normalization to work. ie Normalize something with the same mean
# and std deviation. 
f(imgtup)

(tensor([[-0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888,
          -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888],
         [-0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888,
          -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888],
         [-0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888,
          -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888],
         [-0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, 

Few other things we want in Normalization. We want to be able to serialize it. We want to be able to save the transform we are using to disk including the mean and std deviation.

Secondly we want to be able to undo the normalization so that when we get back an image or whatever from a model we would want to display it which means we need to be able to DENORMALIZE it. 

These capabilities imply we need STATE and to get STATE we need to create a CLASS.  

In [ ]:
class Norm(Transform):
    # To pass in m and s
    #def __init__(self, m, s): self.m, self.s = m,s
    def __init__(self, m, s): 
      super().__init__()
      store_attr(self, 'm,s')
    def encodes(self, x: Tensor): return (x-self.m)/self.s

In [ ]:
m, s = timg.mean(), timg.std()

In [ ]:
f = Norm(m=m, s=s)

In [ ]:
nimg = f(timg)
nimg[12:15]

tensor([[-0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3475,  0.0796,  2.5045,  3.1107,  3.0969,  2.0774,  0.4929, -0.3888, -0.3888, -0.3888,
         -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888],
        [-0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888,  1.0578,  3.0969,  3.0969,  3.1107,  1.1818, -0.2373, -0.3888, -0.3888, -0.3888, -0.3888,
         -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888],
        [-0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.0857,  2.5045,  3.0969,  3.0969,  1.2783, -0.3062, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888,
         -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888]])

In [ ]:
imgtup = (timg, mi)

In [ ]:
f(imgtup)

(tensor([[-0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888,
          -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888],
         [-0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888,
          -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888],
         [-0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888,
          -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888],
         [-0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, 

If you wish to apply the same function to multiple types then you need to do what the following cell does 

In [ ]:
# One way is below
class Norm(Transform):
    def __init__(self, m, s):
        super().__init()
        self.m, self.s = m, s
    def encodes(self, x:Tensor): return (x - self.mean)/self.s
    def encodes(self, x:int):    return (x - self.mean)/self.s

In [ ]:
# Another way
class Norm(Transform):
    def __init__(self, m, s):
        super().__init()
        self.m, self.s = m, s
    def encodes(self, x:Tensor): return (x - self.mean)/self.s

In [ ]:
# Empty class definition ONCE
class Norm(Transform): pass

In [ ]:
# followed by decorator use of that class and put 
# encodes in these different places 
@Norm
def encodes(self, x:Tensor): return (x-self.m)/self.s

In [ ]:
@Norm
def encodes(self, x:int):    return (x-self.m)/self.s

This makes the whole Transform infrastructure modularly extensible. For eg if Normalizing an Audio tensor was different you could just do this and the whole Audio normalizing would occur without any impact on the original code and be its own module thingy. 

So this allows for DATA AUGMENTATION (transforms are used for this if you recall - though we have been discussing Normalization) - we can come up with our own DATA AUGMENTATIONs for our own DATA TYPES. 

The way that THIS DISPATCH SYSTEM WORKS 

In [ ]:
class Norm(Transform):
  def __init__(self, m, s):
    super().__init__()
    self.m, self.s = m, s
  def encodes(self, x:Tensor):
    print('a')
    return (x-self.m)/self.s
  def encodes(self, x:MyTensorImg):
    print('b')
    return (x-self.m)/self.s

In [ ]:
m,s = timg.mean(), timg.std()

In [ ]:
f = Norm(m=m, s=s)

In [ ]:
nimg = f(mti)
nimg[12:15]

b


tensor([[-0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3475,  0.0796,  2.5045,  3.1107,  3.0969,  2.0774,  0.4929, -0.3888, -0.3888, -0.3888,
         -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888],
        [-0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888,  1.0578,  3.0969,  3.0969,  3.1107,  1.1818, -0.2373, -0.3888, -0.3888, -0.3888, -0.3888,
         -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888],
        [-0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.0857,  2.5045,  3.0969,  3.0969,  1.2783, -0.3062, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888,
         -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888]])

Notice that this prints 'b' - Why? Coz MyTensorImg is further down the hierarchy than Tensor is and so that is the more specific match. So encodes uses the most precise type that it can 

In [ ]:
# Another example
class Norm(Transform):
  def __init__(self, m, s):
    super().__init__()
    self.m, self.s = m, s
  def encodes(self, x:Tensor):
    print('a')
    return (x-self.m)/self.s
  def encodes(self, x:numbers.Integral):
    print('b')
    return (x-self.m)/self.s

In [ ]:
m,s = timg.mean(), timg.std()

In [ ]:
f = Norm(m=m, s=s)

In [ ]:
f(3)

b


tensor(-0.3475)

In [ ]:
# Another example
class Norm(Transform):
  def __init__(self, m, s):
    super().__init__()
    self.m, self.s = m, s
  def encodes(self, x:Tensor):
    print('a')
    return (x-self.m)/self.s
  def encodes(self, x:numbers.Integral):
    print('b')
    return (x-self.m)/self.s
  def encodes(self, x:int):
    print('c')
    return (x-self.m)/self.s


In [ ]:
m,s = timg.mean(), timg.std()

In [ ]:
f = Norm(m=m, s=s)

In [ ]:
# Calls the most specialized version
f(3)

c


tensor(-0.3475)

In [ ]:
# Return to basics
class Norm(Transform):
    def __init__(self, m, s):
        super().__init__()
        self.m,self.s = m,s
    def encodes(self, x:MyTensorImg): return (x-self.m)/self.s
    def decodes(self, x:MyTensorImg): return (x*self.s)+self.m

### Going in the opposite direction

In [ ]:
m,s = timg.mean(), timg.std()

In [ ]:
f = Norm(m=m,s=s)

In [ ]:
nimg = f(mti)
nimg[12:15]

tensor([[-0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3475,  0.0796,  2.5045,  3.1107,  3.0969,  2.0774,  0.4929, -0.3888, -0.3888, -0.3888,
         -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888],
        [-0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888,  1.0578,  3.0969,  3.0969,  3.1107,  1.1818, -0.2373, -0.3888, -0.3888, -0.3888, -0.3888,
         -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888],
        [-0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.0857,  2.5045,  3.0969,  3.0969,  1.2783, -0.3062, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888,
         -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888]])

In [ ]:
f.decode(nimg)

MyTensorImg([[  0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,
           0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000],
        [  0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,
           0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000],
        [  0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,
           0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000],
        [  0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,

Works for tuples the same way 

In [ ]:
imgtup = (mti, mi)

In [ ]:
ftup = f(imgtup)

In [ ]:
ftup

(MyTensorImg([[-0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888,
          -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888],
         [-0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888,
          -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888],
         [-0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888,
          -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888],
         [-0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3

In [ ]:
f.decode(ftup)

(MyTensorImg([[  0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,
            0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000],
         [  0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,
            0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000],
         [  0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,
            0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000],
         [  0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   

Not enough to just have one transform like Normalize but need to be able to do other things as well. For eg flip during data augmentation

In [ ]:
def flip_img(x:MyTensorImg): return torch.flip(x, (1,)) if random.random()>0.5 else x

Q: How do we combine the two things together. Normalization and Flipping. 

In [ ]:
# One way would be to do this but if we try it for the tuple DOES NOT WORK
ttup = flip_img(f(imgtup))

TypeError: ignored

In [ ]:
@Transform
def flip_img(x:MyTensorImg): return torch.flip(x, (1,)) if random.random()>0.5 else x

In [ ]:
m,s = timg.mean(),timg.std()

In [ ]:
f= Norm(m=m,s=s)

In [ ]:
ttup = flip_img(f(imgtup))

In [ ]:
ttup

(MyTensorImg([[-0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888,
          -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888],
         [-0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888,
          -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888],
         [-0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888,
          -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888],
         [-0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3888, -0.3

We would like to have ability to define a sequence of such functions (Transforms) and Use them multiple times. One way to do that is by using a Pipeline.

### Pipeline

In [ ]:
# compose is just a thing that runs functions in order 
pipe = compose(f, flip_img) # note the order seq

In [ ]:
ttup = pipe(imgtup)

Problem with above is compose does NOT know anything about Transforms so we cannot do pipe.decode

In [ ]:
pipe.decode(ttup) # Does NOT work

AttributeError: ignored

In [ ]:
# have to do the following
f.decode(flip_img.decode(ttup))

(MyTensorImg([[  0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,
            0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000],
         [  0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,
            0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000],
         [  0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,
            0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000],
         [  0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   

So would be great IF we can use compose to do encoding as well as decoding and to do that we just change compose to Pipeline

In [ ]:
pipe = Pipeline([f, flip_img])

In [ ]:
ttup = pipe(imgtup)

Now we can use decode

In [ ]:
pipe.decode(ttup)

(MyTensorImg([[  0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,
            0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000],
         [  0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,
            0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000],
         [  0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,
            0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000],
         [  0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   

Pipeline knows that if it just gets a function to turn it into a transform so for eg you can remove Transform decorator from flip_img and run this again and 

In [ ]:
# Return to basics
class Norm(Transform):
    def __init__(self, m, s):
        super().__init__()
        self.m,self.s = m,s
    def encodes(self, x:MyTensorImg): return (x-self.m)/self.s
    def decodes(self, x:MyTensorImg): return (x*self.s)+self.m

In [ ]:
# @Transform
def flip_img(x:MyTensorImg): return torch.flip(x, (1,)) if random.random()>0.5 else x

In [ ]:
m,s = timg.mean(),timg.std()

In [ ]:
f = Norm(m=m,s=s)

In [ ]:
pipe = Pipeline([f, flip_img])

In [ ]:
imgtup = (mti,mi)

In [ ]:
ttup = pipe(imgtup)

In [ ]:
pipe.decode(ttup)

(MyTensorImg([[  0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,
            0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000],
         [  0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,
            0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000],
         [  0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,
            0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000],
         [  0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   

We actually do NOT need to define a MyTensorImage class since fastai(??) already has a TensorImage class which we can use and is defined exactly the same way

In [ ]:
'''
Init signature: TensorImage(*args, **kwargs)
Source:         class TensorImage(TensorImageBase): pass
File:           /usr/local/lib/python3.6/dist-packages/fastai2/torch_core.py
Type:           type
'''
TensorImage??

In [ ]:
mti = TensorImage(timg.clone()).float()

In [ ]:
'''
Init signature: Int(*args, **kwargs)
Source:         class Int(int,ShowPrint): pass
File:           /usr/local/lib/python3.6/dist-packages/fastcore/utils.py
Type:           type
'''
Int??

In [ ]:
mi = Int(1)

In [ ]:
# Return to basics
class Norm(Transform):
    def __init__(self, m, s):
        super().__init__()
        self.m,self.s = m,s
    def encodes(self, x:TensorImage): return (x-self.m)/self.s
    def decodes(self, x:TensorImage): return (x*self.s)+self.m

In [ ]:
# @Transform
def flip_img(x:TensorImage): return torch.flip(x, (1,)) if random.random()>0.5 else x

In [ ]:
m,s = timg.mean(),timg.std()

In [ ]:
f = Norm(m=m,s=s)

In [ ]:
imgtup = (mti,mi)

In [ ]:
pipe = Pipeline([f, flip_img])

In [ ]:
ttup = pipe(imgtup)

In [ ]:
pipe.decode(ttup)

(TensorImage([[  0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,
            0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000],
         [  0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,
            0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000],
         [  0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,
            0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000],
         [  0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   

Last piece of the puzzle is to make load_image function a transform as well. So

In [ ]:
# Note that we could make the output a tensor BUT we want to choose a TensorImage
# class so that we know when we decode (for eg) that the tensor is that of an image
# vs say a Tensor resulting from a word representation or char rep or something else

# Could also do this by (x)->TensorImage and then return could be tensor
@Transform
def create_image_tensor(x): return TensorImage(tensor(array(load_image(x))))

In [ ]:
# Instead of having a Transform decorator in previous cell we could also create a Pipeline like so
# That would work too since Pipeline converts functions into Transforms

# timg = Pipeline(create_image_tensor)(fn)

In [ ]:
# Instead of having a Transform decorator in previous cell we could also create a Pipeline
timg = create_image_tensor(fn); timg

TensorImage([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,  26, 213, 169, 121, 121, 192, 121, 121, 121,  89,   0,   0,   0,   0,   0,   0,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,  31, 220, 253, 253, 253, 254, 253, 253, 2

In [ ]:
type(timg)

fastai2.torch_core.TensorImage

In [ ]:
tsub = timg[12:15]
tsub

tensor([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   3,  34, 210, 254, 253, 179,  64,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0, 105, 253, 253, 254, 114,  11,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  22, 210, 253, 253, 121,   6,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0]], dtype=torch.uint8)

In [ ]:
mti = TensorImage(timg.clone()).float()

In [ ]:
type(mti)

fastai2.torch_core.TensorImage

In [ ]:
mi = Int(1)

In [ ]:
# Return to basics
class Norm(Transform):
    def __init__(self, m, s):
        super().__init__()
        self.m,self.s = m,s
    def encodes(self, x:TensorImage): return (x-self.m)/self.s
    def decodes(self, x:TensorImage): return (x*self.s)+self.m

In [ ]:
# @Transform
def flip_img(x:TensorImage): return torch.flip(x, (1,)) if random.random()>0.5 else x

In [ ]:
# Since up top I can converting timg to float and calling it mti
m,s = mti.mean(),mti.std()

In [ ]:
f = Norm(m=m,s=s)

In [ ]:
imgtup = (mti, mi)

In [ ]:
pipe = Pipeline([f, flip_img])

In [ ]:
ttup = pipe(imgtup)

In [ ]:
pipe.decode(ttup)

(TensorImage([[  0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,
            0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000],
         [  0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,
            0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000],
         [  0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,
            0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000],
         [  0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   

Transforms treats passed in values ie x as tuples and behavior is for the function to act on each elem of tuple or listy thing or collection thing x conditioned on types. 

There is *only* ItemTransform now - no TupleTransform. ItemTransform is subclass of Transform and you can inherit from that instead of inheriting from Transform. 

Q - Does Pipeline now change the Transform if it is a ItemTransform - need to check this out. ie does it treat as tuple or as item?.

WT Lecture he says that *all the time* you will get requested behavior.
Reason to support this flexibility of both behaviors is depending on where you are in the data processing pipeline, some time you want tuple behavior and sometime you want item behavior. Specifically, until you collate batch together - so after_item, before_batch callbacks you have two separate pipelines going on - for eg, for image and for label a Pipeline for each. So each pipeline is separately applied eg in Pets as when we are building a dataset one Pipeline is applied to one item at a time (& not tuples), the Pipeline will process an item. (The data has NOT been combined into tuples yet). 

Later on in the process after they are pulled out of the datasets, by the time we get to using a dataloader the Pipeline will operate on tuples. 

## fin -